[project]
name = "bbelderbos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.11",
    "httpx>=0.28.0",
    "jinja2>=3.1.4",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
